# Base configs
baseurl: "/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Alex Lettenberger"
subtitle: "Get a glimpse into my life!"
author: "Alex Lettenberger"
header:
 title: "Photography"
 subtitle: "Alex"
footer:
 name: "Welcome to my photography website!"
 bio: "I'm a developer by trade, but I like to dabble in photography every once in a while. Feel free to check out my photos. I hope you enjoy them!"
 github: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/alex.lettenberger"
  # twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/alex.lettenberger"
  # dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/alex-lettenberger"
  github: "https://www.github.com/alettenb"
  mysite: "https://alettenb.github.io"
